import { decks } from "../data/decks.js";
import { categories, getCategoryById, spreads } from "../data/spreads.js";
import { clearHistory, deleteReading, getHistory, openReading, setFavorite } from "../services/storage-service.js";
import { showToast } from "../components/toast.js";

const normalize = value => String(value ?? "").toLocaleLowerCase("es").normalize("NFD").replace(/[\u0300-\u036f]/g,"");

export function renderHistoryPage() {
  const target=document.querySelector("[data-history-page]"); if (!target) return;
  const requested=new URLSearchParams(location.search).get("id");
  if (requested) { const reading=openReading(requested); if (reading) { renderDetail(target,reading); return; } target.innerHTML=`<div class="friendly-error" role="status"><span aria-hidden="true">☾</span><p class="eyebrow">Lectura no disponible</p><h1>No encontramos esa lectura guardada</h1><p>Puede haber sido eliminada o el enlace puede estar incompleto.</p><a class="button button--primary" href="historial.html">Volver al historial</a></div>`;return; }
  let query="",category="all",spreadId="all",deckId="all",favorites=false,order="newest";
  target.innerHTML=`<header class="history-hero"><p class="eyebrow">Tu recorrido</p><h1>Las preguntas también<br><em>dejan constelaciones</em></h1><p>Solo aparecen aquí las lecturas que decidiste guardar en este dispositivo.</p></header><section class="history-toolbar" aria-label="Buscar y filtrar el historial"><label class="history-search"><span>Buscar</span><input type="search" placeholder="Pregunta, tirada o carta…" data-history-search></label><label><span>Categoría</span><select data-history-category><option value="all">Todas</option>${categories.filter(item=>item.id!=="all").map(item=>`<option value="${item.id}">${escapeHtml(item.name)}</option>`).join("")}</select></label><label><span>Tipo de tirada</span><select data-history-spread><option value="all">Todas</option>${spreads.map(item=>`<option value="${item.id}">${escapeHtml(item.name)}</option>`).join("")}</select></label><label><span>Baraja</span><select data-history-deck><option value="all">Todas</option>${decks.map(item=>`<option value="${item.id}">${escapeHtml(item.name)}</option>`).join("")}</select></label><label><span>Orden</span><select data-history-order><option value="newest">Más recientes</option><option value="oldest">Más antiguas</option></select></label><label class="favorite-filter"><input type="checkbox" data-history-favorites><span>Solo favoritas</span></label></section><div class="history-summary"><p data-history-count aria-live="polite"></p><button class="button button--ghost" type="button" data-clear-history>Borrar historial</button></div><section class="history-list" data-history-list aria-live="polite"></section>`;
  const list=target.querySelector("[data-history-list]"),count=target.querySelector("[data-history-count]");
  list.tabIndex=-1;
  const paint=()=>{
    const all=getHistory(),needle=normalize(query.trim());
    const readings=all.filter(reading=>{const haystack=normalize(`${reading.type?.name} ${reading.question} ${reading.deck?.name} ${(reading.cards??[]).map(card=>card.name).join(" ")}`);return (!needle||haystack.includes(needle))&&(category==="all"||reading.category===category)&&(spreadId==="all"||reading.type?.id===spreadId)&&(deckId==="all"||reading.deck?.id===deckId)&&(!favorites||reading.favorite);}).sort((a,b)=>(order==="oldest"?1:-1)*(new Date(a.date)-new Date(b.date)));
    count.textContent=`${readings.length} ${readings.length===1?"lectura guardada":"lecturas guardadas"}`;
    list.innerHTML=readings.length?readings.map(historyCardTemplate).join(""):emptyTemplate(Boolean(all.length));
    target.querySelector("[data-clear-history]").disabled=!all.length;
  };
  target.querySelector("[data-history-search]").addEventListener("input",event=>{query=event.target.value;paint();});
  target.querySelector("[data-history-category]").addEventListener("change",event=>{category=event.target.value;paint();});
  target.querySelector("[data-history-spread]").addEventListener("change",event=>{spreadId=event.target.value;paint();});
  target.querySelector("[data-history-deck]").addEventListener("change",event=>{deckId=event.target.value;paint();});
  target.querySelector("[data-history-order]").addEventListener("change",event=>{order=event.target.value;paint();});
  target.querySelector("[data-history-favorites]").addEventListener("change",event=>{favorites=event.target.checked;paint();});
  target.addEventListener("click",event=>{
    const favoriteButton=event.target.closest("[data-history-favorite]");
    if(favoriteButton){const id=favoriteButton.dataset.historyFavorite,reading=openReading(id),result=setFavorite(reading.id,!reading.favorite);showToast(result.ok?(reading.favorite?"Lectura quitada de favoritas":"Lectura marcada como favorita"):"No se pudo actualizar la lectura",result.ok?"info":"error");paint();requestAnimationFrame(()=>target.querySelector(`[data-history-favorite="${id}"]`)?.focus());return;}
    const deleteButton=event.target.closest("[data-history-delete]");
    if(deleteButton&&confirm("¿Eliminar esta lectura guardada?")){const result=deleteReading(deleteButton.dataset.historyDelete);showToast(result.ok?"Lectura eliminada":"No se pudo eliminar",result.ok?"info":"error");paint();requestAnimationFrame(()=>list.focus());return;}
    if(event.target.closest("[data-clear-history]")&&confirm("¿Borrar todas las lecturas guardadas? Esta acción no se puede deshacer.")){const result=clearHistory();showToast(result.ok?"Historial borrado":"No se pudo borrar el historial",result.ok?"info":"error");paint();requestAnimationFrame(()=>list.focus());}
  });
  paint();
}

function historyCardTemplate(reading){const cards=(reading.cards??[]).slice(0,3);return `<article class="history-card"><div class="history-card__top"><div><p class="eyebrow">${escapeHtml(reading.type?.name??"Lectura")}</p><time datetime="${escapeHtml(reading.date)}">${formatDate(reading.date)}</time></div><button class="favorite-button ${reading.favorite?"is-favorite":""}" type="button" data-history-favorite="${escapeHtml(reading.id)}" aria-pressed="${reading.favorite}" aria-label="${reading.favorite?"Quitar de favoritas":"Marcar como favorita"}">★</button></div><h2>${escapeHtml(shorten(reading.question||"Consulta abierta",90))}</h2><p class="history-deck">${escapeHtml(reading.deck?.name)}</p><ul class="history-card__cards">${cards.map(card=>`<li><span aria-hidden="true">${escapeHtml(card.symbol||"✦")}</span>${escapeHtml(card.name)} <small>${card.isReversed||card.orientation==="reversed"?"Invertida":"Derecha"}</small></li>`).join("")}</ul><div class="history-card__actions"><a class="button button--secondary" href="historial.html?id=${encodeURIComponent(reading.id)}">Abrir</a><button class="button button--ghost" type="button" data-history-delete="${escapeHtml(reading.id)}">Eliminar</button></div></article>`;}

function renderDetail(target,reading){const interpretation=reading.interpretation??{},category=getCategoryById(reading.category)?.name??reading.category;target.innerHTML=`<article class="saved-reading"><a class="text-link" href="historial.html">← Volver al historial</a><header><div><p class="eyebrow">Lectura guardada · ${formatDate(reading.date)}</p><h1>${escapeHtml(reading.type?.name)}</h1><p>${escapeHtml(reading.question||"Consulta abierta")}</p></div><button class="favorite-button ${reading.favorite?"is-favorite":""}" type="button" data-detail-favorite aria-pressed="${reading.favorite}" aria-label="${reading.favorite?"Quitar de favoritas":"Marcar como favorita"}">★</button></header><dl class="saved-reading__meta"><div><dt>Baraja</dt><dd>${escapeHtml(reading.deck?.name)}</dd></div><div><dt>Categoría</dt><dd>${escapeHtml(category)}</dd></div><div><dt>Cartas</dt><dd>${reading.cards?.length??0}</dd></div></dl><section><h2>Cartas y posiciones</h2><ol class="saved-card-list">${(reading.cards??[]).map((card,index)=>`<li><span>${index+1}</span><div><small>${escapeHtml(card.position?.name??card.position)}</small><strong>${escapeHtml(card.name)}</strong><p>${card.isReversed||card.orientation==="reversed"?"Invertida":"Derecha"}</p></div></li>`).join("")}</ol></section><section class="saved-interpretation"><p class="eyebrow">Síntesis</p><h2>El hilo de la lectura</h2><p>${escapeHtml(interpretation.generalSynthesis)}</p><div><article><h3>Tendencia</h3><p>${escapeHtml(interpretation.tendency)}</p></article><article><h3>Consejo</h3><p>${escapeHtml(interpretation.advice)}</p></article></div></section><div class="saved-reading__actions"><button class="button button--ghost" type="button" data-detail-delete>Eliminar lectura</button><a class="button button--primary" href="lectura.html?tipo=${encodeURIComponent(reading.type?.id??"una-carta")}">Repetir tirada</a></div></article>`;target.querySelector("[data-detail-favorite]").addEventListener("click",()=>{const current=openReading(reading.id),result=setFavorite(reading.id,!current.favorite);if(result.ok)renderDetail(target,result.reading);});target.querySelector("[data-detail-delete]").addEventListener("click",()=>{if(confirm("¿Eliminar esta lectura guardada?")){deleteReading(reading.id);location.href="historial.html";}});}

const emptyTemplate=filtered=>`<div class="empty-state history-empty"><span class="empty-state__symbol" aria-hidden="true">☽</span><h2>${filtered?"No hay coincidencias":"Aún no hay lecturas guardadas"}</h2><p>${filtered?"Prueba cambiando los filtros o la búsqueda.":"Cuando guardes una reflexión, podrás volver a encontrarla aquí."}</p>${filtered?"":'<a class="button button--primary" href="index.html#lecturas">Hacer una lectura</a>'}</div>`;
const formatDate=value=>{const date=new Date(value);return Number.isNaN(date.getTime())?"Fecha no disponible":new Intl.DateTimeFormat("es",{dateStyle:"medium",timeStyle:"short"}).format(date);};
const shorten=(value,max)=>value.length>max?`${value.slice(0,max-1)}…`:value;
const escapeHtml=value=>String(value??"").replace(/[&<>\"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[char]));
